version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

environment:
  CTEST_OUTPUT_ON_FAILURE: 1

install:
    - git submodule update --init --recursive

before_build:
    - cmake --version
    - cmake -G "Visual Studio 15 2017 Win64" -H. -Bbuild

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - cd build
  - ctest -V -C %CONFIGURATION%
